### ISSUE TITLE
checklist: change link in frontend

### ISSUE THREAD

**Issue by aonrobot** [aonrobot/W004-StockMS#32]
For change PULL, DELETE method to POST

### Product
- [ ] PUT : api/product/{id}
   **POST : api/PUT/product/{id}**

- [ ] DELETE : api/product/{product_id}
   **POST : api/DEL/product/{product_id}**
___
### Inventory
- [ ] PUT : api/inventory/quantity/{id}
   **POST : api/PUT/inventory/quantity/{id}**
___
### Document
- [ ] PUT : /api/document/{number}
   **POST : /api/PUT/document/{number}**

- [ ] DELETE : /api/document/{number}
   **POST : api/DEL/document/{number}**

- [ ] DELETE : /api/lineitem/{line item id}
   **POST : api/DEL/lineitem/{line item id}**
